name: bash-brlin
title: The Bourne Again SHell (UNOFFICIAL)
base: core18
version: provided-by-version-script
version-script: git -C parts/bash/src describe --always --dirty --tags | sed 's/^bash-//'
summary: The Bourne Again SHell(Bash) (UNOFFICIAL, EXPERIMENTAL)
description: |
  Bash is an sh-compatible shell that incorporates useful features from the Korn shell (ksh) and C shell (csh). It is intended to conform to the IEEE POSIX P1003.2/ISO 9945.2 Shell and Tools standard. It offers functional improvements over sh for both programming and interactive use. In addition, most sh scripts can be run by Bash without modification.

  The improvements offered by Bash include:

  * Command line editing
  * Unlimited size command history
  * Job Control
  * Shell Functions and Aliases
  * Indexed arrays of unlimited size
  * Integer arithmetic in any base from two to sixty-four

  The maintainer also has a [bash page](https://tiswww.case.edu/php/chet/bash/bashtop.html) which includes [Frequently-Asked-Questions](ftp://ftp.cwru.edu/pub/bash/FAQ).

  NOTE: This is NOT an official distribution of bash, refer the snap's [issue tracker](https://github.com/Lin-Buo-Ren/bash-snap.git) for issues regarding the use of this snap.

grade: stable
confinement: strict

parts:
  patches:
    source: snap/local/patches
    plugin: dump
    organize:
      '*': assets/patches/
    prime:
    - -*

  bash:
    after:
    - patches

    source: git://git.savannah.gnu.org/bash.git
    source-depth: 50

    # For building stable releases
    #source-tag: bash-5.0
    plugin: autotools

    configflags:
    - --datarootdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share

    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current: /

    override-build: |
      snapcraftctl build
      sed \
        --in-place \
        --regexp-extended \
        --file="${SNAPCRAFT_STAGE}"/assets/patches/"Customized bashbug(1) version string.sed" \
        "${SNAPCRAFT_PART_INSTALL}"/bin/bashbug

  # https://github.com/Lin-Buo-Ren/locales-launch-part
  locales-launch:
    plugin: dump
    source: snap/local/launchers
    stage-packages:
    # For localedef(1)
    - libc-bin

    # For locale data used by localedef(1)
    - locales

    # All pre-generated locale data
    # DISABLED: Lots of duplicate data will be included in snap when this is staged, unless the target machine has no resource to generate them in runtime otherwise not using it
    #
    #   Lack of compiled locales breaks gettext based localisation - snapcraft - snapcraft.io
    #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
    #
    #- locales-all

    organize:
      locales-launch: bin/

  # A text editor for bashbug(1)
  nano:
    plugin: nil
    stage-packages:
    - nano

apps:
  bash-brlin:
    adapter: full
    command: bin/bash
    command-chain:
    - bin/locales-launch

  bashbug:
    adapter: full
    command: bin/bashbug
    command-chain:
    - bin/locales-launch
